//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : workflow2.0
//  @ File Name : ActivityStateBean.java
//  @ Date : 2014/7/2
//  @ Author : linp
//
//


package com.papla.cloud.workflow.engine.modal;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;


/**
 * 节点状态表
 **/
@Getter
@Setter
public class ActivityStateBean extends BaseBean {

    private static final long serialVersionUID = 1L;

    private String instanceId;        // 实例ID
    private String actId;            // 节点ID
    private String actCode;        // 节点编码
    private String actState;        // 实例状态
    private Date beginDate;            // 开始时间
    private Date endDate;            // 结束时间
    private int orderBy;            // 执行顺序
    private String isLastStatus;    // 是否最新状态
    private String actCategory;    // 节点类型

}
