//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : workflow2.0
//  @ File Name : ConditionGroupBean.java
//  @ Date : 2014/6/26
//  @ Author : linp
//
//


package com.papla.cloud.workflow.engine.modal;

import java.util.List;

import lombok.Getter;
import lombok.Setter;


/**
 * 流程或节点路由属性条件表
 **/
@Getter
@Setter
public class ConditionGroupBean extends BaseBean {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * 列表条件ID
     **/
    private String groupId;

    /**
     * 条件类型：P-流程级属性，A-节点级属性
     **/
    private String parentType;

    /**
     * 条件类型ID：如果为流程级时，则为流程ID；否则为节点ID
     **/
    private String parentId;

    /**
     * 条件绑定的流程或节点属性编码
     **/
    private String propertyCode;

    /**
     * 条件值，可以为空
     **/
    private String conditionValue;

    /**
     * 条件单元组
     **/
    private List<ConditionBean> conditionList;

}
