//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : workflow2.0
//  @ File Name : InstanceEntityAttrBean.java
//  @ Date : 2014/7/2
//  @ Author : linp
//
//
package com.papla.cloud.workflow.engine.modal;

import lombok.Getter;
import lombok.Setter;


/**
 * 流程实例对应实体属性信息
 **/
@Getter
@Setter
public class InstanceEntityAttrBean extends EntityAttrBean {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * 实例ID
     **/
    private String instanceId;

    /**
     * 属性值
     **/
    private String attrResult;

    /**
     * 是否为系统内置变量
     */
    private String sysInnerVar;


}
