//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : workflow2.0
//  @ File Name : ProcessBean.java
//  @ Date : 2014/6/20
//  @ Author : linp
//
//

package com.papla.cloud.workflow.engine.modal;

import java.util.List;
import java.util.Map;

import lombok.Getter;
import lombok.Setter;

/**
 * 流程基本信息数据项
 **/
@Getter
@Setter
public class ProcessBean extends BaseBean {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * 实体ID
     **/
    private String entityId;

    /**
     * 流程分类
     **/
    private String processCategory;

    /**
     * 组织ID
     **/
    private String orgId;

    /**
     * 流程ID
     **/
    private String id;

    /**
     * 流程部署ID
     */
    private String deployId;

    /**
     * 流程编码
     **/
    private String code;

    /**
     * 流程名称
     **/
    private String name;

    /**
     * 流程版本
     */
    private int processVersion;

    /**
     * 表单类型
     **/
    private String formType;

    /**
     * 静态表单
     **/
    private String staticForm;

    /**
     * 变量表单
     **/
    private String varForm;

    /**
     * 路由表单
     **/
    private String routeForm;

    /**
     * 相邻节点
     **/
    private Object adjacentNode;

    /**
     * 流程内部
     **/
    private String internalFlow;

    /**
     * 提交人规避
     **/
    private String avoidSubmitter;

    /**
     * 提交人变量
     **/
    private String submitterVar;

    /**
     * 绑定条件
     **/
    private String boundCondition;

    /**
     * 撤回函数类型
     **/
    private String revokeType;

    /**
     * 撤回函数
     **/
    private String revokeFunc;

    /**
     * 描述
     */
    private String processDesc;
    /**
     * 流程配置JSON文件
     **/
    private String processJson;
    /**
     * 启用标记
     */
    private String enabled;
    /**
     * 第一次保存标记
     */
    private String fristSave;

    /**
     * 路由表单、路由用户/路由岗位、绑定条件表达式解析结果集
     **/
    private List<ConditionGroupBean> conditionGroupList;

    /**
     * 存储节点对象数组
     **/
    private List<ActivityBean> activityBeanList;

    /**
     * 存储流程连线对象集合
     **/
    private List<TransitionBean> transitionBeanList;

    /**
     * 存储流程属性
     */
    private List<PropertyBean> processPropertyList;

    /**
     * 业务实体属性
     */
    private List<EntityAttrBean> entityAttrBeanList;

    /**
     * 流程测试时传入的实体属性Map
     */
    private Map<String, Object> entityAttrMap;

    private String entityName;
    private String orgName;

}
