//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : workflow2.0
//  @ File Name : PVEnumBean.java
//  @ Date : 2014/6/20
//  @ Author : linp
//
//


package com.papla.cloud.workflow.engine.modal;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;


/**
 * 节点属性值枚举数据项。
 * 如开始节点的枚举表单和通知/会签/抄送节点授权执行人枚举。
 **/
@Getter
@Setter
public class PVEnumBean extends BaseBean {
    /**
     * 枚举值ID
     **/
    private String valueId;

    /**
     * 部署Id
     */
    private String deployId;

    /**
     * 节点ID
     **/
    private String actId;

    /**
     * 节点属性编码
     */
    private String propertyCode;

    /**
     * 节点执行人类型
     **/
    private String executorType;

    /**
     * 节点执行人
     **/
    private String executorValue;

    /**
     * 实例ID
     */
    private String instanceId;


    public PVEnumBean() {
        super();
    }

    public PVEnumBean(String valueId, String actId, String deployId, String propertyCode,
                      String executorType, String executorValue, String createBy,
                      Date createDt) {
        super();
        this.valueId = valueId;
        this.actId = actId;
        this.deployId = deployId;
        this.propertyCode = propertyCode;
        this.executorType = executorType;
        this.executorValue = executorValue;
        this.createBy = createBy;
        this.createDt = createDt;
    }

}
