//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : workflow2.0
//  @ File Name : TransStateBean.java
//  @ Date : 2014/7/2
//  @ Author : linp
//
//


package com.papla.cloud.workflow.engine.modal;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;


/**
 * 连线状态表
 **/
@Getter
@Setter
public class TransStateBean {
    /**
     * 实例ID
     **/
    private String instanceId;

    /**
     * 连线ID
     **/
    private String transitionId;

    /**
     * 实例状态
     **/
    private String transitionState;

    /**
     * 创建时间
     **/
    private Date creationDate;

    /**
     * 创建人
     **/
    private String createBy;

    /**
     * 最后更新时间
     **/
    private Date lastUpdateDate;

    /**
     * 最后更新人
     **/
    private String lastUpdatedBy;

    private int orderBy;

}
