//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : workflow2.0
//  @ File Name : RunInsActPropertyMapper.java
//  @ Date : 2014/7/6
//  @ Author : linp
//
//

package com.papla.cloud.workflow.engine.mapper;

import java.util.List;
import java.util.Map;

import com.papla.cloud.workflow.engine.modal.ActivityPropertyBean;


/**
 * @author zhangfj
 * @version V1.0
 * @ClassName: ProcessDeployActivityPropertyMapper.java
 * @Package com.papla.cloud.wf.mapper
 * @Description: 流程节点属性Mapper： tab - [PAPLA_WF_DEPLOY_ACT_ATTRS]
 * @date 2021年8月24日 下午4:53:04
 */
public interface ProcessDeployActivityPropertyMapper {


    /**
     * @param activityPropertyBeanList
     * @return void
     * @throws Exception
     * @Title saveActivityProperty
     * @Description TODO 批量保存【流程部署】【节点属性】信息
     */
    public void saveActivityProperty(List<ActivityPropertyBean> activityPropertyBeanList) throws Exception;

    /**
     * @param params
     * @return String
     * @throws Exception
     * @Title getInstanceSingleActivityProperty
     * @Description TODO 查询某个【部署节点】的属性值
     */
    public String getInstanceSingleActivityProperty(Map<String, Object> params) throws Exception;

    /**
     * @param params
     * @return ActivityPropertyBean
     * @throws Exception
     * @Title getInstanceSingleActivityPropertyBean
     * @Description TODO 查询某个【部署节点】的属性值信息
     */
    public ActivityPropertyBean getInstanceSingleActivityPropertyBean(Map<String, Object> params) throws Exception;

    /**
     * @param param
     * @return List<ActivityPropertyBean>
     * @throws Exception
     * @Title getActivityPropertyList
     * @Description TODO 查找【部署节点】全部属性列表
     */
    public List<ActivityPropertyBean> getActivityPropertyList(Map<String, Object> param) throws Exception;

}
